title: William Nguyen
logo: /assets/img/official_photo4_cropped.png
description: Welcome to my website. My projects and other information can be seen here.
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
