title: William's website
logo: https://avatars1.githubusercontent.com/u/34763488?s=400&u=7dd349558400e7a9a0a93ac08dd57e9e2187bb9b&v=4
description: Welcome to my website. My projects and other information can be seen here.
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
